<?php

/**
 * Generates /usr/local/etc/bulwark/proftpd/ftp-access.conf with server-level
 * <Limit> blocks using DenyUser to enforce per-user RO/WO/RW access types.
 *
 * Does not require mod_ifsession — DenyUser/AllowAll within <Limit> is core ProFTPD.
 * Called after FTP account create or delete; reloads ProFTPD via privilege::run().
 */
function generateFTPAccessConf($host, $dbUser, $dbPass) {
    try {
        $coreDb = new db_driver("mysql:host=$host;dbname=bulwark_core", $dbUser, $dbPass);
        $stmt = $coreDb->prepare(
            "SELECT ft_user_vc, ft_access_vc FROM x_ftpaccounts WHERE ft_deleted_ts IS NULL"
        );
        $stmt->execute();
        $accounts = $stmt->fetchAll(PDO::FETCH_ASSOC);
    } catch (Exception $e) {
        return false;
    }

    $roUsers = [];
    $woUsers = [];
    foreach ($accounts as $acct) {
        if ($acct['ft_access_vc'] === 'RO') {
            $roUsers[] = $acct['ft_user_vc'];
        } elseif ($acct['ft_access_vc'] === 'WO') {
            $woUsers[] = $acct['ft_user_vc'];
        }
        // RW: full access, no restriction needed
    }

    $lines = [
        "# Auto-generated by Bulwark FTP management — do not edit manually",
        "# Generated: " . date('Y-m-d H:i:s'),
        "",
    ];

    if (!empty($roUsers)) {
        // Read-only: allow downloads, deny all upload/modify operations
        $lines[] = "<Limit STOR STOU APPE MKD XMKD RMD XRMD DELE RNFR RNTO>";
        $lines[] = "  DenyUser " . implode(' ', $roUsers);
        $lines[] = "  AllowAll";
        $lines[] = "</Limit>";
        $lines[] = "";
    }

    if (!empty($woUsers)) {
        // Write-only: allow uploads and listing, deny file downloads
        $lines[] = "<Limit RETR>";
        $lines[] = "  DenyUser " . implode(' ', $woUsers);
        $lines[] = "  AllowAll";
        $lines[] = "</Limit>";
        $lines[] = "";
    }

    $confPath = '/usr/local/etc/bulwark/proftpd/ftp-access.conf';
    if (@file_put_contents($confPath, implode("\n", $lines) . "\n") === false) {
        return false;
    }

    require_once '/usr/local/bulwark/dryden/sys/privilege.class.php';
    privilege::run('proftpd_reload');
    return true;
}
